// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismicT from '@prismicio/types'
import type * as prismic from '@prismicio/client'

type Simplify<T> = {
	[KeyType in keyof T]: T[KeyType]
}
/** Content for Om oss documents */
interface AboutDocumentData {
	/**
	 * Sektion field in *Om oss*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.section_left
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
	 *
	 */
	section_left: prismicT.RichTextField
	/**
	 * Sektion field in *Om oss*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about.section
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
	 *
	 */
	section: prismicT.RichTextField
}
/**
 * Om oss document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<
	Simplify<AboutDocumentData>,
	'about',
	Lang
>
/** Content for Kontakt documents */
interface ContactDocumentData {
	/**
	 * Kontakt field in *Kontakt*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.kontakt[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/group
	 *
	 */
	kontakt: prismicT.GroupField<Simplify<ContactDocumentDataKontaktItem>>
}
/**
 * Item in Kontakt → Kontakt
 *
 */
export interface ContactDocumentDataKontaktItem {
	/**
	 * Kontaktblock field in *Kontakt → Kontakt*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact.kontakt[].contact_block
	 * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
	 *
	 */
	contact_block: prismicT.RichTextField
}
/**
 * Kontakt document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<
	Simplify<ContactDocumentData>,
	'contact',
	Lang
>
/** Content for Dokument documents */
interface DokumentDocumentData {
	/**
	 * Slice Zone field in *Dokument*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: dokument.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/slices
	 *
	 */
	slices: prismicT.SliceZone<DokumentDocumentDataSlicesSlice>
}
/**
 * Slice for *Dokument → Slice Zone*
 *
 */
type DokumentDocumentDataSlicesSlice = DokumentsgrupperingSlice
/**
 * Dokument document from Prismic
 *
 * - **API ID**: `dokument`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DokumentDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<
	Simplify<DokumentDocumentData>,
	'dokument',
	Lang
>
/** Content for Nyhet documents */
interface NyhetDocumentData {
	/**
	 * Datum field in *Nyhet*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nyhet.date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/date
	 *
	 */
	date: prismicT.DateField
	/**
	 * Rubrik field in *Nyhet*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nyhet.header
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	header: prismicT.KeyTextField
	/**
	 * Ingress field in *Nyhet*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nyhet.preamble
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
	 *
	 */
	preamble: prismicT.RichTextField
	/**
	 * Slice Zone field in *Nyhet*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nyhet.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/slices
	 *
	 */
	slices: prismicT.SliceZone<NyhetDocumentDataSlicesSlice>
}
/**
 * Slice for *Nyhet → Slice Zone*
 *
 */
type NyhetDocumentDataSlicesSlice = TextBlockSlice
/**
 * Nyhet document from Prismic
 *
 * - **API ID**: `nyhet`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NyhetDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<
	Simplify<NyhetDocumentData>,
	'nyhet',
	Lang
>
/** Content for Nyheter documents */
interface NyheterDocumentData {
	/**
	 * Slice Zone field in *Nyheter*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nyheter.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/slices
	 *
	 */
	slices: prismicT.SliceZone<NyheterDocumentDataSlicesSlice>
}
/**
 * Slice for *Nyheter → Slice Zone*
 *
 */
type NyheterDocumentDataSlicesSlice = BildTextSlice
/**
 * Nyheter document from Prismic
 *
 * - **API ID**: `nyheter`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NyheterDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<
	Simplify<NyheterDocumentData>,
	'nyheter',
	Lang
>
/** Content for Inställningar documents */
interface SiteSettingsDocumentData {
	/**
	 * Information field in *Inställningar*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: site_settings.information
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
	 *
	 */
	information: prismicT.RichTextField
	/**
	 * Meny field in *Inställningar*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: site_settings.menu[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/group
	 *
	 */
	menu: prismicT.GroupField<Simplify<SiteSettingsDocumentDataMenuItem>>
}
/**
 * Item in Inställningar → Meny
 *
 */
export interface SiteSettingsDocumentDataMenuItem {
	/**
	 * Länk field in *Inställningar → Meny*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: site_settings.menu[].link
	 * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
	 *
	 */
	link: prismicT.LinkField
	/**
	 * Länk text field in *Inställningar → Meny*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: site_settings.menu[].link_text
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	link_text: prismicT.KeyTextField
}
/**
 * Inställningar document from Prismic
 *
 * - **API ID**: `site_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteSettingsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<
	Simplify<SiteSettingsDocumentData>,
	'site_settings',
	Lang
>
/** Content for Start documents */
interface StartDocumentData {
	/**
	 * Slice Zone field in *Start*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: start.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/slices
	 *
	 */
	slices: prismicT.SliceZone<StartDocumentDataSlicesSlice>
}
/**
 * Slice for *Start → Slice Zone*
 *
 */
type StartDocumentDataSlicesSlice = HeroSlice | NyheterSlice
/**
 * Start document from Prismic
 *
 * - **API ID**: `start`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StartDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<
	Simplify<StartDocumentData>,
	'start',
	Lang
>
export type AllDocumentTypes =
	| AboutDocument
	| ContactDocument
	| DokumentDocument
	| NyhetDocument
	| NyheterDocument
	| SiteSettingsDocument
	| StartDocument
/**
 * Primary content in BildText → Primary
 *
 */
interface BildTextSliceDefaultPrimary {
	/**
	 * Titel field in *BildText → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bild_text.primary.title
	 * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
	 *
	 */
	title: prismicT.TitleField
	/**
	 * Ingress field in *BildText → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bild_text.primary.description
	 * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
	 *
	 */
	description: prismicT.RichTextField
	/**
	 * Bild field in *BildText → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: bild_text.primary.image
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	image: prismicT.ImageField<never>
}
/**
 * Default variation for BildText Slice
 *
 * - **API ID**: `default`
 * - **Description**: `BildText`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BildTextSliceDefault = prismicT.SharedSliceVariation<
	'default',
	Simplify<BildTextSliceDefaultPrimary>,
	never
>
/**
 * Slice variation for *BildText*
 *
 */
type BildTextSliceVariation = BildTextSliceDefault
/**
 * BildText Shared Slice
 *
 * - **API ID**: `bild_text`
 * - **Description**: `BildText`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type BildTextSlice = prismicT.SharedSlice<'bild_text', BildTextSliceVariation>
/**
 * Primary content in Dokumentsgruppering → Primary
 *
 */
interface DokumentsgrupperingSliceDefaultPrimary {
	/**
	 * Titel field in *Dokumentsgruppering → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: dokumentsgruppering.primary.title
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	title: prismicT.KeyTextField
}
/**
 * Item in Dokumentsgruppering → Items
 *
 */
export interface DokumentsgrupperingSliceDefaultItem {
	/**
	 * Länk field in *Dokumentsgruppering → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: dokumentsgruppering.items[].link
	 * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
	 *
	 */
	link: prismicT.LinkField
	/**
	 * Länk text field in *Dokumentsgruppering → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: dokumentsgruppering.items[].link_text
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	link_text: prismicT.KeyTextField
	/**
	 * Nedladdningsbar field in *Dokumentsgruppering → Items*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: dokumentsgruppering.items[].downloadable
	 * - **Documentation**: https://prismic.io/docs/core-concepts/boolean
	 *
	 */
	downloadable: prismicT.BooleanField
}
/**
 * Default variation for Dokumentsgruppering Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Dokumentsgruppering`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DokumentsgrupperingSliceDefault = prismicT.SharedSliceVariation<
	'default',
	Simplify<DokumentsgrupperingSliceDefaultPrimary>,
	Simplify<DokumentsgrupperingSliceDefaultItem>
>
/**
 * Slice variation for *Dokumentsgruppering*
 *
 */
type DokumentsgrupperingSliceVariation = DokumentsgrupperingSliceDefault
/**
 * Dokumentsgruppering Shared Slice
 *
 * - **API ID**: `dokumentsgruppering`
 * - **Description**: `Dokumentsgruppering`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DokumentsgrupperingSlice = prismicT.SharedSlice<
	'dokumentsgruppering',
	DokumentsgrupperingSliceVariation
>
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceDefaultPrimary {
	/**
	 * Titel field in *Hero → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: Huvudtitel
	 * - **API ID Path**: hero.primary.title
	 * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
	 *
	 */
	title: prismicT.TitleField
	/**
	 * Ingress field in *Hero → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Ingress för startsidan
	 * - **API ID Path**: hero.primary.description
	 * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
	 *
	 */
	description: prismicT.RichTextField
	/**
	 * Bakgrundsbild field in *Hero → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.primary.image
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	image: prismicT.ImageField<never>
	/**
	 * Länk field in *Hero → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.primary.link
	 * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
	 *
	 */
	link: prismicT.LinkField
	/**
	 * Länktext field in *Hero → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.primary.link_text
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	link_text: prismicT.KeyTextField
}
/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceDefault = prismicT.SharedSliceVariation<
	'default',
	Simplify<HeroSliceDefaultPrimary>,
	never
>
/**
 * Slice variation for *Hero*
 *
 */
type HeroSliceVariation = HeroSliceDefault
/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSlice = prismicT.SharedSlice<'hero', HeroSliceVariation>
/**
 * Primary content in Nyheter → Primary
 *
 */
interface NyheterSliceDefaultPrimary {
	/**
	 * Titel field in *Nyheter → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nyheter.primary.title
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	title: prismicT.KeyTextField
}
/**
 * Default variation for Nyheter Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Nyheter`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NyheterSliceDefault = prismicT.SharedSliceVariation<
	'default',
	Simplify<NyheterSliceDefaultPrimary>,
	never
>
/**
 * Slice variation for *Nyheter*
 *
 */
type NyheterSliceVariation = NyheterSliceDefault
/**
 * Nyheter Shared Slice
 *
 * - **API ID**: `nyheter`
 * - **Description**: `Nyheter`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NyheterSlice = prismicT.SharedSlice<'nyheter', NyheterSliceVariation>
/**
 * Primary content in TextBlock → Primary
 *
 */
interface TextBlockSliceDefaultPrimary {
	/**
	 * Text field in *TextBlock → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_block.primary.text
	 * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
	 *
	 */
	text: prismicT.RichTextField
}
/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TextBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextBlockSliceDefault = prismicT.SharedSliceVariation<
	'default',
	Simplify<TextBlockSliceDefaultPrimary>,
	never
>
/**
 * Slice variation for *TextBlock*
 *
 */
type TextBlockSliceVariation = TextBlockSliceDefault
/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: `TextBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextBlockSlice = prismicT.SharedSlice<'text_block', TextBlockSliceVariation>
declare module '@prismicio/client' {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>
	}
	namespace Content {
		export type {
			AboutDocumentData,
			AboutDocument,
			ContactDocumentData,
			ContactDocumentDataKontaktItem,
			ContactDocument,
			DokumentDocumentData,
			DokumentDocumentDataSlicesSlice,
			DokumentDocument,
			NyhetDocumentData,
			NyhetDocumentDataSlicesSlice,
			NyhetDocument,
			NyheterDocumentData,
			NyheterDocumentDataSlicesSlice,
			NyheterDocument,
			SiteSettingsDocumentData,
			SiteSettingsDocumentDataMenuItem,
			SiteSettingsDocument,
			StartDocumentData,
			StartDocumentDataSlicesSlice,
			StartDocument,
			AllDocumentTypes,
			BildTextSliceDefaultPrimary,
			BildTextSliceDefault,
			BildTextSliceVariation,
			BildTextSlice,
			DokumentsgrupperingSliceDefaultPrimary,
			DokumentsgrupperingSliceDefaultItem,
			DokumentsgrupperingSliceDefault,
			DokumentsgrupperingSliceVariation,
			DokumentsgrupperingSlice,
			HeroSliceDefaultPrimary,
			HeroSliceDefault,
			HeroSliceVariation,
			HeroSlice,
			NyheterSliceDefaultPrimary,
			NyheterSliceDefault,
			NyheterSliceVariation,
			NyheterSlice,
			TextBlockSliceDefaultPrimary,
			TextBlockSliceDefault,
			TextBlockSliceVariation,
			TextBlockSlice
		}
	}
}
