// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from '@prismicio/types'
import type * as prismic from '@prismicio/client'

type Simplify<T> = {
	[KeyType in keyof T]: T[KeyType]
}
/** Content for Nyhet documents */
interface NyhetDocumentData {
	/**
	 * Datum field in *Nyhet*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nyhet.date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/date
	 *
	 */
	date: prismicT.DateField
	/**
	 * Rubrik field in *Nyhet*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nyhet.header
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	header: prismicT.KeyTextField
	/**
	 * Ingress field in *Nyhet*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nyhet.preamble
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
	 *
	 */
	preamble: prismicT.RichTextField
	/**
	 * Slice Zone field in *Nyhet*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nyhet.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/slices
	 *
	 */
	slices: prismicT.SliceZone<NyhetDocumentDataSlicesSlice>
}
/**
 * Slice for *Nyhet → Slice Zone*
 *
 */
type NyhetDocumentDataSlicesSlice = TextBlockSlice
/**
 * Nyhet document from Prismic
 *
 * - **API ID**: `nyhet`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NyhetDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<
	Simplify<NyhetDocumentData>,
	'nyhet',
	Lang
>
/** Content for Inställningar documents */
interface SiteSettingsDocumentData {
	/**
	 * Information field in *Inställningar*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: site_settings.information
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
	 *
	 */
	information: prismicT.RichTextField
}
/**
 * Inställningar document from Prismic
 *
 * - **API ID**: `site_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteSettingsDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<
	Simplify<SiteSettingsDocumentData>,
	'site_settings',
	Lang
>
/** Content for Start documents */
interface StartDocumentData {
	/**
	 * Slice Zone field in *Start*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: start.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/core-concepts/slices
	 *
	 */
	slices: prismicT.SliceZone<StartDocumentDataSlicesSlice>
}
/**
 * Slice for *Start → Slice Zone*
 *
 */
type StartDocumentDataSlicesSlice = HeroSlice | NyheterSlice
/**
 * Start document from Prismic
 *
 * - **API ID**: `start`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type StartDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<
	Simplify<StartDocumentData>,
	'start',
	Lang
>
export type AllDocumentTypes = NyhetDocument | SiteSettingsDocument | StartDocument
/**
 * Primary content in Hero → Primary
 *
 */
interface HeroSliceDefaultPrimary {
	/**
	 * Titel field in *Hero → Primary*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: Huvudtitel
	 * - **API ID Path**: hero.primary.title
	 * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
	 *
	 */
	title: prismicT.TitleField
	/**
	 * Ingress field in *Hero → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Ingress för startsidan
	 * - **API ID Path**: hero.primary.description
	 * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
	 *
	 */
	description: prismicT.RichTextField
	/**
	 * Bakgrundsbild field in *Hero → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.primary.image
	 * - **Documentation**: https://prismic.io/docs/core-concepts/image
	 *
	 */
	image: prismicT.ImageField<never>
	/**
	 * Länk field in *Hero → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.primary.link
	 * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
	 *
	 */
	link: prismicT.LinkField
	/**
	 * Länktext field in *Hero → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.primary.link_text
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	link_text: prismicT.KeyTextField
}
/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSliceDefault = prismicT.SharedSliceVariation<
	'default',
	Simplify<HeroSliceDefaultPrimary>,
	never
>
/**
 * Slice variation for *Hero*
 *
 */
type HeroSliceVariation = HeroSliceDefault
/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: `Hero`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HeroSlice = prismicT.SharedSlice<'hero', HeroSliceVariation>
/**
 * Primary content in Nyheter → Primary
 *
 */
interface NyheterSliceDefaultPrimary {
	/**
	 * Titel field in *Nyheter → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: nyheter.primary.title
	 * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
	 *
	 */
	title: prismicT.KeyTextField
}
/**
 * Default variation for Nyheter Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Nyheter`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NyheterSliceDefault = prismicT.SharedSliceVariation<
	'default',
	Simplify<NyheterSliceDefaultPrimary>,
	never
>
/**
 * Slice variation for *Nyheter*
 *
 */
type NyheterSliceVariation = NyheterSliceDefault
/**
 * Nyheter Shared Slice
 *
 * - **API ID**: `nyheter`
 * - **Description**: `Nyheter`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NyheterSlice = prismicT.SharedSlice<'nyheter', NyheterSliceVariation>
/**
 * Primary content in TextBlock → Primary
 *
 */
interface TextBlockSliceDefaultPrimary {
	/**
	 * Text field in *TextBlock → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text_block.primary.text
	 * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
	 *
	 */
	text: prismicT.RichTextField
}
/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TextBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextBlockSliceDefault = prismicT.SharedSliceVariation<
	'default',
	Simplify<TextBlockSliceDefaultPrimary>,
	never
>
/**
 * Slice variation for *TextBlock*
 *
 */
type TextBlockSliceVariation = TextBlockSliceDefault
/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: `TextBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextBlockSlice = prismicT.SharedSlice<'text_block', TextBlockSliceVariation>
declare module '@prismicio/client' {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>
	}
	namespace Content {
		export type {
			NyhetDocumentData,
			NyhetDocumentDataSlicesSlice,
			NyhetDocument,
			SiteSettingsDocumentData,
			SiteSettingsDocument,
			StartDocumentData,
			StartDocumentDataSlicesSlice,
			StartDocument,
			AllDocumentTypes,
			HeroSliceDefaultPrimary,
			HeroSliceDefault,
			HeroSliceVariation,
			HeroSlice,
			NyheterSliceDefaultPrimary,
			NyheterSliceDefault,
			NyheterSliceVariation,
			NyheterSlice,
			TextBlockSliceDefaultPrimary,
			TextBlockSliceDefault,
			TextBlockSliceVariation,
			TextBlockSlice
		}
	}
}
