// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero';
import Nyheter from './Nyheter';
import TextBlock from './TextBlock';

export {
	Hero,
	Nyheter,
	TextBlock,
};

export const components = {
	hero: Hero,
	nyheter: Nyheter,
	text_block: TextBlock,
};
