// Code generated by Slice Machine. DO NOT EDIT.

import BildText from './BildText';
import Dokumentsgruppering from './Dokumentsgruppering';
import Hero from './Hero';
import Nyheter from './Nyheter';
import TextBlock from './TextBlock';

export {
	BildText,
	Dokumentsgruppering,
	Hero,
	Nyheter,
	TextBlock,
};

export const components = {
	bild_text: BildText,
	dokumentsgruppering: Dokumentsgruppering,
	hero: Hero,
	nyheter: Nyheter,
	text_block: TextBlock,
};
